"""Type stubs for xbmcaddon module."""
from __future__ import annotations

class Addon:
    def __init__(self, id: str = ...) -> None: ...
    def getAddonInfo(self, id: str) -> str: ...
    def getSetting(self, id: str) -> str: ...
    def getSettingBool(self, id: str) -> bool: ...
    def getSettingInt(self, id: str) -> int: ...
    def getSettingNumber(self, id: str) -> float: ...
    def getSettingString(self, id: str) -> str: ...
    def setSetting(self, id: str, value: str) -> None: ...
    def setSettingBool(self, id: str, value: bool) -> bool: ...
    def setSettingInt(self, id: str, value: int) -> bool: ...
    def setSettingNumber(self, id: str, value: float) -> bool: ...
    def setSettingString(self, id: str, value: str) -> bool: ...
    def openSettings(self) -> None: ...
    def getLocalizedString(self, id: int) -> str: ...
