"""Type stubs for xbmcplugin module."""
from __future__ import annotations

from typing import Any

# Sort methods
SORT_METHOD_NONE: int
SORT_METHOD_LABEL: int
SORT_METHOD_LABEL_IGNORE_THE: int
SORT_METHOD_DATE: int
SORT_METHOD_SIZE: int
SORT_METHOD_FILE: int
SORT_METHOD_UNSORTED: int
SORT_METHOD_VIDEO_TITLE: int

def addDirectoryItem(handle: int, url: str, listitem: Any, isFolder: bool = ..., totalItems: int = ...) -> bool: ...
def addDirectoryItems(handle: int, items: list[tuple[str, Any, bool]], totalItems: int = ...) -> bool: ...
def endOfDirectory(handle: int, succeeded: bool = ..., updateListing: bool = ..., cacheToDisc: bool = ...) -> None: ...
def setResolvedUrl(handle: int, succeeded: bool, listitem: Any) -> None: ...
def addSortMethod(handle: int, sortMethod: int, label2Mask: str = ...) -> None: ...
def getSetting(handle: int, id: str) -> str: ...
def setSetting(handle: int, id: str, value: str) -> None: ...
def setContent(handle: int, content: str) -> None: ...
def setPluginCategory(handle: int, category: str) -> None: ...
def setPluginFanart(handle: int, image: str = ..., color1: str = ..., color2: str = ..., color3: str = ...) -> None: ...
def setProperty(handle: int, key: str, value: str) -> None: ...
