"""Type stubs for xbmc module."""
from __future__ import annotations

from typing import Any

# Log levels
LOGDEBUG: int
LOGINFO: int
LOGWARNING: int
LOGERROR: int
LOGFATAL: int
LOGNONE: int

def log(msg: str, level: int = ...) -> None: ...
def executebuiltin(function: str, wait: bool = ...) -> None: ...
def getCondVisibility(condition: str) -> bool: ...
def getInfoLabel(infotag: str) -> str: ...
def getInfoImage(infotag: str) -> str: ...
def getLocalizedString(id: int) -> str: ...
def getSkinDir() -> str: ...
def getLanguage(format: int = ..., region: bool = ...) -> str: ...
def translatePath(path: str) -> str: ...
def sleep(timemillis: int) -> None: ...
def executeJSONRPC(jsonrpccommand: str) -> str: ...

class Keyboard:
    def __init__(self, default: str = ..., heading: str = ..., hidden: bool = ...) -> None: ...
    def doModal(self, autoclose: int = ...) -> None: ...
    def setDefault(self, default: str) -> None: ...
    def setHeading(self, heading: str) -> None: ...
    def setHiddenInput(self, hidden: bool) -> None: ...
    def getText(self) -> str: ...
    def isConfirmed(self) -> bool: ...

class Monitor:
    def __init__(self) -> None: ...
    def onSettingsChanged(self) -> None: ...
    def onScreensaverActivated(self) -> None: ...
    def onScreensaverDeactivated(self) -> None: ...
    def onDPMSActivated(self) -> None: ...
    def onDPMSDeactivated(self) -> None: ...
    def waitForAbort(self, timeout: float = ...) -> bool: ...
    def abortRequested(self) -> bool: ...
