"""Type stubs for xbmcvfs module."""
from __future__ import annotations

from typing import Any

def copy(source: str, destination: str) -> bool: ...
def delete(file: str) -> bool: ...
def rename(file: str, newFileName: str) -> bool: ...
def exists(path: str) -> bool: ...
def mkdir(path: str) -> bool: ...
def mkdirs(path: str) -> bool: ...
def rmdir(path: str, force: bool = ...) -> bool: ...
def listdir(path: str) -> tuple[list[str], list[str]]: ...
def translatePath(path: str) -> str: ...

class File:
    def __init__(self, filepath: str, mode: str = ...) -> None: ...
    def close(self) -> None: ...
    def read(self, bytes: int = ...) -> bytes: ...
    def readBytes(self, numbytes: int = ...) -> bytes: ...
    def write(self, buffer: bytes | str) -> bool: ...
    def size(self) -> int: ...
    def seek(self, seekBytes: int, iWhence: int = ...) -> int: ...
    def tell(self) -> int: ...

class Stat:
    def __init__(self, path: str) -> None: ...
    def st_atime(self) -> int: ...
    def st_ctime(self) -> int: ...
    def st_dev(self) -> int: ...
    def st_gid(self) -> int: ...
    def st_ino(self) -> int: ...
    def st_mode(self) -> int: ...
    def st_mtime(self) -> int: ...
    def st_nlink(self) -> int: ...
    def st_size(self) -> int: ...
    def st_uid(self) -> int: ...
