"""Type stubs for xbmcgui module."""
from __future__ import annotations

from typing import Any

INPUT_ALPHANUM: int
INPUT_NUMERIC: int
INPUT_DATE: int
INPUT_TIME: int
INPUT_IPADDRESS: int
INPUT_PASSWORD: int

def getCurrentWindowId() -> int: ...
def getCurrentWindowDialogId() -> int: ...

class Window:
    def __init__(self, existingWindowId: int = ...) -> None: ...
    def show(self) -> None: ...
    def setFocus(self, control: Any) -> None: ...
    def setFocusId(self, controlId: int) -> None: ...
    def getFocus(self) -> Any: ...
    def getFocusId(self) -> int: ...
    def removeControl(self, control: Any) -> None: ...
    def removeControls(self, controls: list[Any]) -> None: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def setProperty(self, key: str, value: str) -> None: ...
    def getProperty(self, key: str) -> str: ...
    def clearProperty(self, key: str) -> None: ...
    def clearProperties(self) -> None: ...
    def close(self) -> None: ...
    def doModal(self) -> None: ...
    def addControl(self, control: Any) -> None: ...
    def addControls(self, controls: list[Any]) -> None: ...
    def getControl(self, controlId: int) -> Any: ...

class WindowXML(Window):
    def __init__(self, xmlFilename: str, scriptPath: str, defaultSkin: str = ..., defaultRes: str = ...) -> None: ...

class WindowXMLDialog(WindowXML):
    def __init__(self, xmlFilename: str, scriptPath: str, defaultSkin: str = ..., defaultRes: str = ...) -> None: ...

class Dialog:
    def __init__(self) -> None: ...
    def ok(self, heading: str, message: str) -> bool: ...
    def yesno(self, heading: str, message: str, nolabel: str = ..., yeslabel: str = ...) -> bool: ...
    def select(self, heading: str, list: list[str | Any], autoclose: int = ..., preselect: int = ..., useDetails: bool = ...) -> int: ...
    def multiselect(self, heading: str, options: list[str | Any], autoclose: int = ..., preselect: list[int] = ..., useDetails: bool = ...) -> list[int] | None: ...
    def textviewer(self, heading: str, text: str, usemono: bool = ...) -> None: ...
    def browse(self, type: int, heading: str, shares: str, mask: str = ..., useThumbs: bool = ..., treatAsFolder: bool = ..., defaultt: str = ..., enableMultiple: bool = ...) -> str | list[str]: ...
    def browseSingle(self, type: int, heading: str, shares: str, mask: str = ..., useThumbs: bool = ..., treatAsFolder: bool = ..., defaultt: str = ...) -> str: ...
    def browseMultiple(self, type: int, heading: str, shares: str, mask: str = ..., useThumbs: bool = ..., treatAsFolder: bool = ..., defaultt: str = ...) -> list[str]: ...
    def numeric(self, type: int, heading: str, defaultt: str = ..., bHiddenInput: bool = ...) -> str: ...
    def notification(self, heading: str, message: str, icon: str = ..., time: int = ..., sound: bool = ...) -> None: ...
    def input(self, heading: str, defaultt: str = ..., type: int = ..., option: int = ..., autoclose: int = ...) -> str: ...
    def contextmenu(self, list: list[str]) -> int: ...

class DialogProgress:
    def __init__(self) -> None: ...
    def create(self, heading: str, message: str = ...) -> None: ...
    def update(self, percent: int, message: str = ...) -> None: ...
    def close(self) -> None: ...
    def iscanceled(self) -> bool: ...

class ListItem:
    def __init__(self, label: str = ..., label2: str = ..., path: str = ..., offscreen: bool = ...) -> None: ...
    def getLabel(self) -> str: ...
    def getLabel2(self) -> str: ...
    def setLabel(self, label: str) -> None: ...
    def setLabel2(self, label: str) -> None: ...
    def setArt(self, dictionary: dict[str, str]) -> None: ...
    def setIconImage(self, icon: str) -> None: ...
    def setThumbnailImage(self, thumb: str) -> None: ...
    def setProperty(self, key: str, value: str) -> None: ...
    def getProperty(self, key: str) -> str: ...
    def setPath(self, path: str) -> None: ...
    def getPath(self) -> str: ...
    def select(self, selected: bool) -> None: ...
    def isSelected(self) -> bool: ...
