# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 U3knOwn

"""Static lookup tables keyed on the lowercase codec or language id from Kodi."""

# Video codec map (VideoPlayer.VideoCodec -> display label)
VIDEO_CODEC_MAP = {
    "3iv2":       "3ivx",
    "av1":        "AV1",
    "avc1":       "H.264",
    "div2":       "DivX",
    "div3":       "DivX",
    "divx":       "DivX",
    "divx 4":     "DivX",
    "dx50":       "DivX",
    "flv":        "FLV",
    "h264":       "H.264",
    "hev1":       "H.265",
    "hevc":       "H.265",
    "hvc1":       "H.265",
    "microsoft":  "Microsoft Video",
    "mp42":       "MS MPEG-4 v2",
    "mp43":       "MS MPEG-4 v3",
    "mp4v":       "MPEG-4",
    "mpeg1":      "MPEG-1",
    "mpeg1video": "MPEG-1",
    "mpeg2":      "MPEG-2",
    "mpeg2video": "MPEG-2",
    "mpeg4":      "MPEG-4",
    "mpg4":       "MPEG-4",
    "rv40":       "RealVideo 9/10",
    "svq1":       "Sorenson Video 1",
    "svq3":       "Sorenson Video 3",
    "theora":     "Theora",
    "vc-1":       "VC-1",
    "vc1":        "VC-1",
    "vp6f":       "On2 VP6",
    "vp8":        "VP8",
    "vp9":        "VP9",
    "wmv":        "WMV",
    "wmv2":       "WMV 8",
    "wmv3":       "WMV 9",
    "wvc1":       "VC-1",
    "xvid":       "XviD",
}

# Subtitle codec map (VideoPlayer.SubtitleCodec -> display label)
SUBTITLE_CODEC_MAP = {
    "ass":               "ASS",
    "dvb_subtitle":      "DVB-SUB",
    "dvb_teletext":      "DVB-Text",
    "dvd_subtitle":      "VobSub",
    "hdmv_pgs_subtitle": "PGS",
    "microdvd":          "MicroDVD",
    "mov_text":          "Timed Text",
    "mpl2":              "MPL2",
    "realtext":          "RealText",
    "sami":              "SAMI",
    "srt":               "SubRip",
    "ssa":               "SSA",
    "subrip":            "SubRip",
    "text":              "Text",
    "ttml":              "TTML",
    "vplayer":           "VPlayer",
    "webvtt":            "WebVTT",
    "xsub":              "XSUB",
}

# Audio codec map (VideoPlayer.AudioCodec -> display label)
AUDIO_CODEC_MAP = {
    # AAC
    "aac":             "AAC",
    "aac_latm":        "AAC",
    "aac_lc":          "AAC-LC",
    "he_aac":          "HE-AAC",
    "he_aac_v2":       "HE-AAC v2",
    "aac_ssr":         "AAC-SSR",
    "aac_ltp":         "AAC-LTP",

    # Dolby
    "ac3":             "Dolby Digital",
    "dolbydigital":    "Dolby Digital",
    "eac3":            "Dolby Digital Plus",
    "eac3_ddp_atmos":  "Dolby Digital Plus",
    "truehd":          "Dolby TrueHD",
    "truehd_atmos":    "Dolby TrueHD",

    # DTS
    "dca":             "DTS",
    "dts":             "DTS",
    "dts_96_24":       "DTS 96/24",
    "dts_es":          "DTS-ES",
    "dts_express":     "DTS Express",
    "dtshd":           "DTS-HD",
    "dtshd_ma":        "DTS-HD MA",
    "dtshd_hra":       "DTS-HD HRA",
    "dtshd_ma_x":      "DTS:X",
    "dtshd_ma_x_imax": "DTS:X",

    # Lossless / PCM
    "alac":            "ALAC",
    "flac":            "FLAC",
    "pcm":             "PCM",
    "pcm_bluray":      "LPCM",
    "pcm_s16le":       "PCM",
    "pcm_s24le":       "PCM",
    "wav":             "WAV",
    "wavpack":         "WavPack",

    # Compressed
    "ape":             "Monkey's Audio (APE)",
    "mp1":             "MP1",
    "mp2":             "MP2",
    "mp3":             "MP3",
    "mp3float":        "MP3",
    "ogg":             "Ogg Vorbis",
    "opus":            "Opus",
    "vorbis":          "Vorbis",
    "wmapro":          "WMA Pro",
    "wmav2":           "WMA",

    # Misc
    "aif":             "AIFF",
    "aifc":            "AIFF-C",
    "aiff":            "AIFF",
    "avc":             "AVC",
    "cdda":            "CD Audio",
}

# Audio codec -> splash logo (codecs/*.png in the skin's media folder).
# Unmapped codecs show no audio logo.
AUDIO_LOGO_MAP = {
    # AAC
    "aac":             "codecs/AAC.png",
    "aac_latm":        "codecs/AAC_LATM.png",
    "aac_lc":          "codecs/AAC-LC.png",
    "he_aac":          "codecs/HE-AAC.png",
    "he_aac_v2":       "codecs/HE_AAC_v2.png",
    "aac_ssr":         "codecs/AAC_SSR.png",
    "aac_ltp":         "codecs/AAC_LTP.png",

    # Dolby
    "ac3":             "codecs/Dolby_Digital.png",
    "dolbydigital":    "codecs/Dolby_Digital.png",
    "eac3":            "codecs/Dolby_Digital_Plus.png",
    "eac3_ddp_atmos":  "codecs/Dolby_Digital_Plus_Atmos.png",
    "truehd":          "codecs/Dolby_TrueHD.png",
    "truehd_atmos":    "codecs/Dolby_TrueHD_Atmos.png",

    # DTS
    "dca":             "codecs/DTS.png",
    "dts":             "codecs/DTS.png",
    "dts_96_24":       "codecs/DTS-96-24.png",
    "dts_es":          "codecs/DTS-ES.png",
    "dts_express":     "codecs/DTS-Express.png",
    "dtshd":           "codecs/DTS-HD-MA.png",
    "dtshd_ma":        "codecs/DTS-HD-MA.png",
    "dtshd_hra":       "codecs/DTS-HD-HRA.png",
    "dtshd_ma_x":      "codecs/DTSX.png",
    "dtshd_ma_x_imax": "codecs/IMAX.png",

    # Lossless / PCM
    "flac":            "codecs/FLAC.png",
    "pcm":             "codecs/PCM.png",
    "pcm_bluray":      "codecs/PCM.png",
    "pcm_s16le":       "codecs/PCM.png",
    "pcm_s24le":       "codecs/PCM.png",

    # Compressed
    "mp1":             "codecs/MP1.png",
    "mp2":             "codecs/MP2.png",
    "mp3":             "codecs/MP3.png",
    "mp3float":        "codecs/MP3.png",
    "ogg":             "codecs/OGG.png",
    "opus":            "codecs/OPUS.png",
    "vorbis":          "codecs/VORBIS.png",
}

# HDR type -> splash logo (codecs/*.png).  The empty string maps to the SDR
# logo, so every video gets a video logo.
HDR_LOGO_MAP = {
    "":            "codecs/SDR.png",
    "hdr10":       "codecs/HDR10.png",
    "hdr10+":      "codecs/HDR10Plus.png",
    "hlg":         "codecs/HLG.png",
    "dolbyvision": "codecs/Dolby_Vision.png",
}

# Replacements for the logos above while IMAX material plays (see
# ui.splash._current_logos, which falls back to the plain logo when one is
# not installed).  HLG and SDR have no IMAX variant.
IMAX_LOGO_MAP = {
    "hdr10":       "codecs/HDR10_IMAX.png",
    "hdr10+":      "codecs/HDR10Plus_IMAX.png",
    "dolbyvision": "codecs/Dolby_Vision_IMAX.png",
}

# Channel count -> surround layout string
CHANNELS_MAP = {
    1:  "1.0",
    2:  "2.0",
    4:  "4.0",
    5:  "5.0",
    6:  "5.1",
    7:  "6.1",
    8:  "7.1",
    10: "9.1",
}

# Channel count -> full speaker-label string
CHANNELS_INPUT_MAP = {
    1:  "Mono",
    2:  "FL, FR",
    3:  "FL, FR, LFE",
    4:  "FL, FR, BL, BR",
    5:  "FL, FR, LFE, BL, BR",
    6:  "FL, FR, FC, LFE, SL, SR",
    7:  "FL, FR, FC, LFE, BC, SL, SR",
    8:  "FL, FR, FC, LFE, BL, BR, SL, SR",
    9:  "FL, FR, FC, LFE, BL, BR, SL, SR, FWL",
    10: "FL, FR, FC, LFE, BL, BR, SL, SR, FWL, FWR",
}

# Channel count -> speaker-layout graphic in the channels/<box>/ folder
# chosen by properties.py.  Unmapped counts show no graphic.
CHANNELS_ICON_MAP = {
    1: "1.0",
    2: "2.0",
    3: "2.1",
    4: "3.1",
    5: "4.1",
    6: "5.1",
    7: "6.1",
    8: "7.1",
}

# Codecs with height channels: the Atmos and DTS:X families (IMAX Enhanced is
# DTS:X based).  Kodi reports only the channel count, so height speakers are
# inferred from the codec.
HEIGHT_CHANNEL_CODECS = frozenset({
    "eac3_ddp_atmos",
    "truehd_atmos",
    "dtshd_ma_x",
    "dtshd_ma_x_imax",
})

# Channel count -> speaker-layout graphic for the codecs above.
CHANNELS_ICON_HEIGHT_MAP = {
    6: "5.1.2",
    8: "7.1.2",
}

# ISO 639-2/B language code -> native language name
LANGUAGE_MAP = {
    "abk": "Apsua",
    "ace": "Baksa Acèh",
    "ach": "Lwo",
    "ada": "Dangme",
    "ady": "Adygebze",
    "aar": "Qafaraf",
    "afh": "Afrihili",
    "afr": "Afrikaans",
    "afa": "Lughat 'afru-aswiatia",
    "ain": "Aynu itak",
    "aka": "Akan",
    "akk": "Akkadû",
    "alb": "Shqip",
    "ale": "Unangam Tunuu",
    "alg": "Algonquin",
    "tut": "Altaic",
    "amh": "Amarinya",
    "anp": "Angika",
    "apa": "Ndee",
    "ara": "Arabiya",
    "arg": "Aragonés",
    "arp": "Hinóno'eitíít",
    "arw": "Arawak",
    "arm": "Hayeren",
    "rup": "Armãneashti",
    "art": "Lingua artificial",
    "asm": "Axomiya",
    "ast": "Asturianu",
    "ath": "Athabaskan",
    "aus": "Australian",
    "map": "Austronesian",
    "ava": "Awar mácʼal",
    "ave": "Avestan",
    "awa": "Awadhi",
    "aym": "Aymar aru",
    "aze": "Azərbaycanca",
    "ban": "Basa Bali",
    "bat": "Baltu",
    "bal": "Balochi",
    "bam": "Bamanankan",
    "bai": "Bamileke",
    "bad": "Banda",
    "bnt": "Bantu",
    "bas": "Mbene",
    "bak": "Bashqortsa",
    "baq": "Euskara",
    "btk": "Batak",
    "bej": "Bedawiyet",
    "bel": "Belaruskaja",
    "bem": "Chibemba",
    "ben": "Bangla",
    "ber": "Tamazight",
    "bho": "Bhojpuri",
    "bih": "Bihari",
    "bik": "Bikol",
    "bin": "Edo",
    "bis": "Bislama",
    "byn": "Blin",
    "zbl": "Blissymbols",
    "nob": "Norsk Bokmål",
    "bos": "Bosanski",
    "bra": "Braj Bhasha",
    "bre": "Brezhoneg",
    "bug": "Basa Ugi",
    "bul": "Bălgarski",
    "bua": "Buryaad xelen",
    "bur": "Myanmara sa",
    "cad": "Caddo",
    "cat": "Català",
    "cau": "Caucasian",
    "ceb": "Sinugboanon",
    "cel": "Celtic",
    "cai": "Central American Indian",
    "khm": "Khmer",
    "chg": "Chagatai",
    "cmc": "Chamic",
    "cha": "Chamoru",
    "che": "Noxchin mott",
    "chr": "Tsalagi",
    "chy": "Tsėhésenėstsestse",
    "chb": "Chibcha",
    "nya": "Chichewa",
    "chi": "Zhongwen",
    "chn": "Chinook Wawa",
    "chp": "Dënesųłıne",
    "cho": "Chahta",
    "chu": "Slověnskyi język",
    "chk": "Foosun Chuuk",
    "chv": "Čăvašla",
    "nwc": "Nepal Bhasa",
    "syc": "Suryaya",
    "cop": "Met Remenkhemi",
    "cor": "Kernowek",
    "cos": "Corsu",
    "cre": "Nēhiyawēwin",
    "mus": "Mvskoke",
    "crp": "Creole",
    "cpe": "English-based creole",
    "cpf": "Créole à base française",
    "cpp": "Crioulo de base portuguesa",
    "crh": "Qırımtatarca",
    "hrv": "Hrvatski",
    "cus": "Cushitic",
    "cze": "Čeština",
    "dak": "Dakȟótiyapi",
    "dan": "Dansk",
    "dar": "Dargwa",
    "del": "Lanape",
    "din": "Thuɔŋjaŋ",
    "div": "Dhivehi",
    "doi": "Dogri",
    "dgr": "Tłı̨chǫ Yatiì",
    "dra": "Dravidian",
    "dua": "Duálá",
    "dum": "Middelnederlands",
    "dut": "Nederlands",
    "dyu": "Julakan",
    "dzo": "Dzongkha",
    "frs": "Seeltersk",
    "efi": "Efik",
    "eka": "Ekajuk",
    "elx": "Elamite",
    "eng": "English",
    "enm": "Middle English",
    "ang": "Englisc",
    "myv": "Erzjan kel'",
    "epo": "Esperanto",
    "est": "Eesti",
    "ewe": "Ewęgbe",
    "ewo": "Ewondo",
    "fan": "Fang",
    "fat": "Fanti",
    "fao": "Føroyskt",
    "fij": "Na Vosa Vakaviti",
    "fil": "Filipino",
    "fin": "Suomi",
    "fiu": "Finno-Ugric",
    "fon": "Fongbe",
    "fre": "Français",
    "frm": "Moyen français",
    "fro": "Ancien français",
    "fur": "Furlan",
    "ful": "Fulfulde",
    "gaa": "Gã",
    "gla": "Gàidhlig",
    "car": "Kari'nja",
    "glg": "Galego",
    "lug": "Luganda",
    "gay": "Gayo",
    "gba": "Gbaya",
    "gez": "Ge'ez",
    "geo": "Kartuli",
    "ger": "Deutsch",
    "gmh": "Diutisk",
    "goh": "Diutisk",
    "gem": "Germanic",
    "gil": "Taetae ni Kiribati",
    "gon": "Gondi",
    "gor": "Bahasa Gorontalo",
    "got": "Gutisko razda",
    "grb": "Grebo",
    "grc": "Ellēnikē",
    "gre": "Elliniká",
    "grn": "Avañe'ẽ",
    "guj": "Gujarati",
    "gwi": "Gwich'in",
    "hai": "Xaat Kíl",
    "hat": "Kreyòl ayisyen",
    "hau": "Hausa",
    "haw": "ʻŌlelo Hawaiʻi",
    "heb": "Ivrit",
    "her": "Oshiherero",
    "hil": "Hiligaynon",
    "him": "Pahari",
    "hin": "Hindi",
    "hmo": "Hiri Motu",
    "hit": "Nesili",
    "hmn": "Hmoob",
    "hun": "Magyar",
    "hup": "Hupa",
    "iba": "Iban",
    "ice": "Íslenska",
    "ido": "Ido",
    "ibo": "Asụsụ Igbo",
    "ijo": "Ijo",
    "ilo": "Ilokano",
    "smn": "Anarâškielâ",
    "inc": "Indo-Aryan",
    "ine": "Indo-European",
    "ind": "Bahasa Indonesia",
    "inh": "Ghalghaj mott",
    "ina": "Interlingua",
    "ile": "Interlingue",
    "iku": "Inuktitut",
    "ipk": "Iñupiatun",
    "ira": "Iranian",
    "gle": "Gaeilge",
    "mga": "Middle Irish",
    "sga": "Old Irish",
    "iro": "Iroquoian",
    "ita": "Italiano",
    "jpn": "Nihongo",
    "jav": "Basa Jawa",
    "jrb": "Al-Yahudiyya al-Arabiya",
    "jpr": "Dzhidi",
    "kbd": "Qabardjébze",
    "kab": "Taqbaylit",
    "kac": "Jingpho",
    "kal": "Kalaallisut",
    "xal": "Halmg keln",
    "kam": "Kikamba",
    "kan": "Kannada",
    "kau": "Kanuri",
    "kaa": "Qaraqalpaq tili",
    "krc": "Qaračaj-malkar til",
    "krl": "Karjalan kieli",
    "kar": "Karen",
    "kas": "Kashmiri",
    "csb": "Kaszëbsczi",
    "kaw": "Kawi",
    "kaz": "Qazaq tili",
    "kha": "Kynshi",
    "khi": "Khoisan",
    "kho": "Sakan",
    "kik": "Gikuyu",
    "kmb": "Kimbundu",
    "kin": "Ikinyarwanda",
    "kir": "Kyrgyzcha",
    "tlh": "tlhIngan Hol",
    "kom": "Komi kyv",
    "kon": "Kikongo",
    "kok": "Konkani",
    "kor": "Hangugo",
    "kos": "Kosrae",
    "kpe": "Kpelle",
    "kro": "Kru",
    "kua": "Oshikwanyama",
    "kum": "Kumuk til",
    "kur": "Kurdî",
    "kru": "Kurukh",
    "kut": "Ktunaxa",
    "lad": "Dzhudeo-Espanyiol",
    "lah": "Lahnda",
    "lam": "Lamba",
    "day": "Land Dayak",
    "lao": "Phasa Lao",
    "lat": "Latina",
    "lav": "Latviešu",
    "lez": "Lezgi č'al",
    "lim": "Limburgs",
    "lin": "Lingála",
    "lit": "Lietuvių",
    "jbo": "Lojban",
    "nds": "Plattdüütsch",
    "dsb": "Dolnoserbski",
    "loz": "Silozi",
    "lub": "Tshiluba",
    "lua": "Luba-Lulua",
    "lui": "Cham'teela",
    "smj": "Julevsámegiella",
    "lun": "Chilunda",
    "luo": "Dholuo",
    "lus": "Mizo ṭawng",
    "ltz": "Lëtzebuergesch",
    "mac": "Makedonski",
    "mad": "Basa Madura",
    "mag": "Magahi",
    "mai": "Maithili",
    "mak": "Basa Mangkasara",
    "mlg": "Malagasy",
    "may": "Bahasa Melayu",
    "mal": "Malayalam",
    "mlt": "Malti",
    "mnc": "Manju gisun",
    "mdr": "Mandar",
    "man": "Mandingo",
    "mni": "Meitei lon",
    "mno": "Manobo",
    "glv": "Gaelg",
    "mao": "Te Reo Māori",
    "arn": "Mapudungun",
    "mar": "Marathi",
    "chm": "Marij jylme",
    "mah": "Kajin M̧ajeļ",
    "mwr": "Marwari",
    "mas": "Maa",
    "myn": "Mayan",
    "men": "Mɛnde yia",
    "mic": "Mìgmawei",
    "min": "Baso Minangkabau",
    "mwl": "Mirandés",
    "moh": "Kanienʼkéha",
    "mdf": "Mokshan kyel'",
    "mkh": "Mon-Khmer",
    "lol": "Lomongo",
    "mon": "Mongol xele",
    "mos": "Mooré",
    "mul": "Multiple languages",
    "mun": "Munda",
    "nqo": "N'Ko",
    "nah": "Nāhuatl",
    "nau": "Dorerin Naoero",
    "nav": "Diné bizaad",
    "nde": "IsiNdebele saseNdoronini",
    "nbl": "IsiNdebele",
    "ndo": "Oshindonga",
    "nap": "Napulitano",
    "new": "Nepal Bhasa",
    "nep": "Nepali",
    "nia": "Li Niha",
    "nic": "Niger-Kordofanian",
    "ssa": "Nilo-Saharan",
    "niu": "Ko e vagahau Niuē",
    "zxx": "No linguistic content",
    "nog": "Nogaj tili",
    "non": "Dönsk tunga",
    "nai": "North American Indian",
    "frr": "Frasch",
    "sme": "Davvisámegiella",
    "nno": "Norsk Nynorsk",
    "nor": "Norsk",
    "nub": "Nubian",
    "nym": "Kinyamwezi",
    "nyn": "Runyankore",
    "nyo": "Runyoro",
    "nzi": "Nzema",
    "oci": "Occitan",
    "arc": "Aramaya",
    "oji": "Anishinaabemowin",
    "ori": "Odia",
    "orm": "Afaan Oromoo",
    "osa": "Wazhazhe ie",
    "oss": "Iron ævzag",
    "oto": "Otomanguean",
    "pal": "Pārsīg",
    "pau": "Tekoi ra Belau",
    "pli": "Pāḷi",
    "pam": "Kapampangan",
    "pag": "Salitan Pangasinan",
    "pan": "Panjabi",
    "pap": "Papiamentu",
    "paa": "Papuan",
    "nso": "Sesotho sa Leboa",
    "per": "Farsi",
    "peo": "Old Persian",
    "phi": "Philippine",
    "phn": "Phoenician",
    "pon": "Mahsen en Pohnpei",
    "pol": "Polski",
    "por": "Português",
    "pra": "Prakrit",
    "pro": "Ancien occitan",
    "pus": "Pashto",
    "que": "Runa Simi",
    "raj": "Rajasthani",
    "rap": "Vananga Rapa Nui",
    "rar": "Māori Kūki 'Āirani",
    "roa": "Romance",
    "rum": "Română",
    "roh": "Rumantsch",
    "rom": "Romani čhib",
    "run": "Ikirundi",
    "rus": "Russkij",
    "sal": "Salishan",
    "sam": "Aramit Šamrayim",
    "smi": "Sami",
    "smo": "Gagana Sāmoa",
    "sad": "Sandawe",
    "sag": "Sängö",
    "san": "Samskrta",
    "sat": "Santali",
    "srd": "Sardu",
    "sas": "Sasak",
    "sco": "Scots",
    "sel": "Seeľkup šənak",
    "sem": "Semitic",
    "srp": "Srpski",
    "srr": "Seereer",
    "shn": "Tai Shan",
    "sna": "chiShona",
    "iii": "Nuosuhxop",
    "scn": "Sicilianu",
    "sid": "Sidaamu Afoo",
    "sgn": "Sign Language",
    "bla": "Siksikáí'powahsin",
    "snd": "Sindhi",
    "sin": "Sinhala",
    "sit": "Sino-Tibetan",
    "sio": "Siouan",
    "sms": "Säämsgjõll",
    "den": "Dene Zhatıé",
    "sla": "Slavic",
    "slo": "Slovenčina",
    "slv": "Slovenščina",
    "sog": "Sogdian",
    "som": "Soomaali",
    "son": "Soŋay",
    "snk": "Soninkanxanne",
    "wen": "Serbšćina",
    "sot": "Sesotho",
    "sai": "South American Indian",
    "alt": "Tyva dyl",
    "sma": "Åarjelsaemiegiele",
    "spa": "Español",
    "srn": "Sranantongo",
    "suk": "Kisukuma",
    "sux": "Eme-gir",
    "sun": "Basa Sunda",
    "sus": "Susu",
    "swa": "Kiswahili",
    "ssw": "SiSwati",
    "swe": "Svenska",
    "gsw": "Schwiizerdütsch",
    "syr": "Surayt",
    "tgl": "Tagalog",
    "tah": "Reo Tahiti",
    "tai": "Tai",
    "tgk": "Tojikī",
    "tmh": "Tamasheq",
    "tam": "Tamizh",
    "tat": "Tatarça",
    "tel": "Telugu",
    "ter": "Tereno",
    "tet": "Tetun",
    "tha": "Phasa Thai",
    "tib": "Bodskad",
    "tig": "Tigré",
    "tir": "Tigrinya",
    "tem": "K聲mne",
    "tiv": "Tiv",
    "tli": "Lingít",
    "tpi": "Tok Pisin",
    "tkl": "Tokelau",
    "tog": "Chitonga",
    "ton": "Faka-Tonga",
    "tsi": "Sm'algyax",
    "tso": "Xitsonga",
    "tsn": "Setswana",
    "tum": "Chitumbuka",
    "tup": "Tupí",
    "tur": "Türkçe",
    "ota": "Lisān-ı Osmānī",
    "tuk": "Türkmençe",
    "tvl": "Te Gana Tuvalu",
    "tyv": "Tyva dyl",
    "twi": "Twi",
    "udm": "Udmurt kyl",
    "uga": "Ugaritic",
    "uig": "Uyghurche",
    "ukr": "Ukrajinska",
    "umb": "Úmbúndú",
    "mis": "Uncoded",
    "und": "Undetermined",
    "hsb": "Hornjoserbsce",
    "urd": "Urdu",
    "uzb": "Oʻzbekcha",
    "vai": "Vai",
    "ven": "Tshivenda",
    "vie": "Tiếng Việt",
    "vol": "Volapük",
    "vot": "Vađđa tšeeli",
    "wak": "Wakashan",
    "wal": "Wolaitta",
    "wln": "Walon",
    "war": "Winaray",
    "was": "Wá:šiw ʔítlu",
    "wel": "Cymraeg",
    "fry": "Frysk",
    "wol": "Wolof",
    "xho": "isiXhosa",
    "sah": "Saxa tyla",
    "yao": "Chiyao",
    "yap": "Thin nu Wa'ab",
    "yid": "Yiddish",
    "yor": "Yorùbá",
    "ypk": "Yupik",
    "znd": "Zande",
    "zap": "Diidxazá",
    "zza": "Zazaki",
    "zen": "Zenaga",
    "zha": "Vahcuengh",
    "zul": "isiZulu",
    "zun": "Shiwi'ma",
}

# ISO 639-2/B language code -> ISO 639-2/T code (uppercase)
LANGUAGE_MAP_SHORT = {
    "abk": "ABK",
    "ace": "ACE",
    "ach": "ACH",
    "ada": "ADA",
    "ady": "ADY",
    "aar": "AAR",
    "afh": "AFH",
    "afr": "AFR",
    "afa": "AFA",
    "ain": "AIN",
    "aka": "AKA",
    "akk": "AKK",
    "alb": "SQI",
    "ale": "ALE",
    "alg": "ALG",
    "tut": "TUT",
    "amh": "AMH",
    "anp": "ANP",
    "apa": "APA",
    "ara": "ARA",
    "arg": "ARG",
    "arp": "ARP",
    "arw": "ARW",
    "arm": "HYE",
    "rup": "RUP",
    "art": "ART",
    "asm": "ASM",
    "ast": "AST",
    "ath": "ATH",
    "aus": "AUS",
    "map": "MAP",
    "ava": "AVA",
    "ave": "AVE",
    "awa": "AWA",
    "aym": "AYM",
    "aze": "AZE",
    "ban": "BAN",
    "bat": "BAT",
    "bal": "BAL",
    "bam": "BAM",
    "bai": "BAI",
    "bad": "BAD",
    "bnt": "BNT",
    "bas": "BAS",
    "bak": "BAK",
    "baq": "EUS",
    "btk": "BTK",
    "bej": "BEJ",
    "bel": "BEL",
    "bem": "BEM",
    "ben": "BEN",
    "ber": "BER",
    "bho": "BHO",
    "bih": "BIH",
    "bik": "BIK",
    "bin": "BIN",
    "bis": "BIS",
    "byn": "BYN",
    "zbl": "ZBL",
    "nob": "NOB",
    "bos": "BOS",
    "bra": "BRA",
    "bre": "BRE",
    "bug": "BUG",
    "bul": "BUL",
    "bua": "BUA",
    "bur": "MYA",
    "cad": "CAD",
    "cat": "CAT",
    "cau": "CAU",
    "ceb": "CEB",
    "cel": "CEL",
    "cai": "CAI",
    "khm": "KHM",
    "chg": "CHG",
    "cmc": "CMC",
    "cha": "CHA",
    "che": "CHE",
    "chr": "CHR",
    "chy": "CHY",
    "chb": "CHB",
    "nya": "NYA",
    "chi": "ZHO",
    "chn": "CHN",
    "chp": "CHP",
    "cho": "CHO",
    "chu": "CHU",
    "chk": "CHK",
    "chv": "CHV",
    "nwc": "NWC",
    "syc": "SYC",
    "cop": "COP",
    "cor": "COR",
    "cos": "COS",
    "cre": "CRE",
    "mus": "MUS",
    "crp": "CRP",
    "cpe": "CPE",
    "cpf": "CPF",
    "cpp": "CPP",
    "crh": "CRH",
    "hrv": "HRV",
    "cus": "CUS",
    "cze": "CES",
    "dak": "DAK",
    "dan": "DAN",
    "dar": "DAR",
    "del": "DEL",
    "din": "DIN",
    "div": "DIV",
    "doi": "DOI",
    "dgr": "DGR",
    "dra": "DRA",
    "dua": "DUA",
    "dum": "DUM",
    "dut": "NLD",
    "dyu": "DYU",
    "dzo": "DZO",
    "frs": "FRS",
    "efi": "EFI",
    "eka": "EKA",
    "elx": "ELX",
    "eng": "ENG",
    "enm": "ENM",
    "ang": "ANG",
    "myv": "MYV",
    "epo": "EPO",
    "est": "EST",
    "ewe": "EWE",
    "ewo": "EWO",
    "fan": "FAN",
    "fat": "FAT",
    "fao": "FAO",
    "fij": "FIJ",
    "fil": "FIL",
    "fin": "FIN",
    "fiu": "FIU",
    "fon": "FON",
    "fre": "FRA",
    "frm": "FRM",
    "fro": "FRO",
    "fur": "FUR",
    "ful": "FUL",
    "gaa": "GAA",
    "gla": "GLA",
    "car": "CAR",
    "glg": "GLG",
    "lug": "LUG",
    "gay": "GAY",
    "gba": "GBA",
    "gez": "GEZ",
    "geo": "KAT",
    "ger": "DEU",
    "gmh": "GMH",
    "goh": "GOH",
    "gem": "GEM",
    "gil": "GIL",
    "gon": "GON",
    "gor": "GOR",
    "got": "GOT",
    "grb": "GRB",
    "grc": "GRC",
    "gre": "ELL",
    "grn": "GRN",
    "guj": "GUJ",
    "gwi": "GWI",
    "hai": "HAI",
    "hat": "HAT",
    "hau": "HAU",
    "haw": "HAW",
    "heb": "HEB",
    "her": "HER",
    "hil": "HIL",
    "him": "HIM",
    "hin": "HIN",
    "hmo": "HMO",
    "hit": "HIT",
    "hmn": "HMN",
    "hun": "HUN",
    "hup": "HUP",
    "iba": "IBA",
    "ice": "ISL",
    "ido": "IDO",
    "ibo": "IBO",
    "ijo": "IJO",
    "ilo": "ILO",
    "smn": "SMN",
    "inc": "INC",
    "ine": "INE",
    "ind": "IND",
    "inh": "INH",
    "ina": "INA",
    "ile": "ILE",
    "iku": "IKU",
    "ipk": "IPK",
    "ira": "IRA",
    "gle": "GLE",
    "mga": "MGA",
    "sga": "SGA",
    "iro": "IRO",
    "ita": "ITA",
    "jpn": "JPN",
    "jav": "JAV",
    "jrb": "JRB",
    "jpr": "JPR",
    "kbd": "KBD",
    "kab": "KAB",
    "kac": "KAC",
    "kal": "KAL",
    "xal": "XAL",
    "kam": "KAM",
    "kan": "KAN",
    "kau": "KAU",
    "kaa": "KAA",
    "krc": "KRC",
    "krl": "KRL",
    "kar": "KAR",
    "kas": "KAS",
    "csb": "CSB",
    "kaw": "KAW",
    "kaz": "KAZ",
    "kha": "KHA",
    "khi": "KHI",
    "kho": "KHO",
    "kik": "KIK",
    "kmb": "KMB",
    "kin": "KIN",
    "kir": "KIR",
    "tlh": "TLH",
    "kom": "KOM",
    "kon": "KON",
    "kok": "KOK",
    "kor": "KOR",
    "kos": "KOS",
    "kpe": "KPE",
    "kro": "KRO",
    "kua": "KUA",
    "kum": "KUM",
    "kur": "KUR",
    "kru": "KRU",
    "kut": "KUT",
    "lad": "LAD",
    "lah": "LAH",
    "lam": "LAM",
    "day": "DAY",
    "lao": "LAO",
    "lat": "LAT",
    "lav": "LAV",
    "lez": "LEZ",
    "lim": "LIM",
    "lin": "LIN",
    "lit": "LIT",
    "jbo": "JBO",
    "nds": "NDS",
    "dsb": "DSB",
    "loz": "LOZ",
    "lub": "LUB",
    "lua": "LUA",
    "lui": "LUI",
    "smj": "SMJ",
    "lun": "LUN",
    "luo": "LUO",
    "lus": "LUS",
    "ltz": "LTZ",
    "mac": "MKD",
    "mad": "MAD",
    "mag": "MAG",
    "mai": "MAI",
    "mak": "MAK",
    "mlg": "MLG",
    "may": "MSA",
    "mal": "MAL",
    "mlt": "MLT",
    "mnc": "MNC",
    "mdr": "MDR",
    "man": "MAN",
    "mni": "MNI",
    "mno": "MNO",
    "glv": "GLV",
    "mao": "MRI",
    "arn": "ARN",
    "mar": "MAR",
    "chm": "CHM",
    "mah": "MAH",
    "mwr": "MWR",
    "mas": "MAS",
    "myn": "MYN",
    "men": "MEN",
    "mic": "MIC",
    "min": "MIN",
    "mwl": "MWL",
    "moh": "MOH",
    "mdf": "MDF",
    "mkh": "MKH",
    "lol": "LOL",
    "mon": "MON",
    "mos": "MOS",
    "mul": "MUL",
    "mun": "MUN",
    "nqo": "NQO",
    "nah": "NAH",
    "nau": "NAU",
    "nav": "NAV",
    "nde": "NDE",
    "nbl": "NBL",
    "ndo": "NDO",
    "nap": "NAP",
    "new": "NEW",
    "nep": "NEP",
    "nia": "NIA",
    "nic": "NIC",
    "ssa": "SSA",
    "niu": "NIU",
    "zxx": "ZXX",
    "nog": "NOG",
    "non": "NON",
    "nai": "NAI",
    "frr": "FRR",
    "sme": "SME",
    "nno": "NNO",
    "nor": "NOR",
    "nub": "NUB",
    "nym": "NYM",
    "nyn": "NYN",
    "nyo": "NYO",
    "nzi": "NZI",
    "oci": "OCI",
    "arc": "ARC",
    "oji": "OJI",
    "ori": "ORI",
    "orm": "ORM",
    "osa": "OSA",
    "oss": "OSS",
    "oto": "OTO",
    "pal": "PAL",
    "pau": "PAU",
    "pli": "PLI",
    "pam": "PAM",
    "pag": "PAG",
    "pan": "PAN",
    "pap": "PAP",
    "paa": "PAA",
    "nso": "NSO",
    "per": "FAS",
    "peo": "PEO",
    "phi": "PHI",
    "phn": "PHN",
    "pon": "PON",
    "pol": "POL",
    "por": "POR",
    "pra": "PRA",
    "pro": "PRO",
    "pus": "PUS",
    "que": "QUE",
    "raj": "RAJ",
    "rap": "RAP",
    "rar": "RAR",
    "roa": "ROA",
    "rum": "RON",
    "roh": "ROH",
    "rom": "ROM",
    "run": "RUN",
    "rus": "RUS",
    "sal": "SAL",
    "sam": "SAM",
    "smi": "SMI",
    "smo": "SMO",
    "sad": "SAD",
    "sag": "SAG",
    "san": "SAN",
    "sat": "SAT",
    "srd": "SRD",
    "sas": "SAS",
    "sco": "SCO",
    "sel": "SEL",
    "sem": "SEM",
    "srp": "SRP",
    "srr": "SRR",
    "shn": "SHN",
    "sna": "SNA",
    "iii": "III",
    "scn": "SCN",
    "sid": "SID",
    "sgn": "SGN",
    "bla": "BLA",
    "snd": "SND",
    "sin": "SIN",
    "sit": "SIT",
    "sio": "SIO",
    "sms": "SMS",
    "den": "DEN",
    "sla": "SLA",
    "slo": "SLK",
    "slv": "SLV",
    "sog": "SOG",
    "som": "SOM",
    "son": "SON",
    "snk": "SNK",
    "wen": "WEN",
    "sot": "SOT",
    "sai": "SAI",
    "alt": "ALT",
    "sma": "SMA",
    "spa": "SPA",
    "srn": "SRN",
    "suk": "SUK",
    "sux": "SUX",
    "sun": "SUN",
    "sus": "SUS",
    "swa": "SWA",
    "ssw": "SSW",
    "swe": "SWE",
    "gsw": "GSW",
    "syr": "SYR",
    "tgl": "TGL",
    "tah": "TAH",
    "tai": "TAI",
    "tgk": "TGK",
    "tmh": "TMH",
    "tam": "TAM",
    "tat": "TAT",
    "tel": "TEL",
    "ter": "TER",
    "tet": "TET",
    "tha": "THA",
    "tib": "BOD",
    "tig": "TIG",
    "tir": "TIR",
    "tem": "TEM",
    "tiv": "TIV",
    "tli": "TLI",
    "tpi": "TPI",
    "tkl": "TKL",
    "tog": "TOG",
    "ton": "TON",
    "tsi": "TSI",
    "tso": "TSO",
    "tsn": "TSN",
    "tum": "TUM",
    "tup": "TUP",
    "tur": "TUR",
    "ota": "OTA",
    "tuk": "TUK",
    "tvl": "TVL",
    "tyv": "TYV",
    "twi": "TWI",
    "udm": "UDM",
    "uga": "UGA",
    "uig": "UIG",
    "ukr": "UKR",
    "umb": "UMB",
    "mis": "MIS",
    "und": "UND",
    "hsb": "HSB",
    "urd": "URD",
    "uzb": "UZB",
    "vai": "VAI",
    "ven": "VEN",
    "vie": "VIE",
    "vol": "VOL",
    "vot": "VOT",
    "wak": "WAK",
    "wal": "WAL",
    "wln": "WLN",
    "war": "WAR",
    "was": "WAS",
    "wel": "CYM",
    "fry": "FRY",
    "wol": "WOL",
    "xho": "XHO",
    "sah": "SAH",
    "yao": "YAO",
    "yap": "YAP",
    "yid": "YID",
    "yor": "YOR",
    "ypk": "YPK",
    "znd": "ZND",
    "zap": "ZAP",
    "zza": "ZZA",
    "zen": "ZEN",
    "zha": "ZHA",
    "zul": "ZUL",
    "zun": "ZUN",
}
