from typing import IO, Iterator, Literal, Sequence

class Element:
    tag: str
    attrib: dict[str, str]
    text: str | None
    tail: str | None

    def __init__(self, tag: str, attrib: dict[str, str] = ..., **extra: str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Element]: ...
    def __getitem__(self, index: int) -> Element: ...
    def append(self, subelement: Element) -> None: ...
    def extend(self, elements: Sequence[Element]) -> None: ...
    def insert(self, index: int, subelement: Element) -> None: ...
    def remove(self, subelement: Element) -> None: ...
    def find(self, path: str, namespaces: dict[str, str] | None = ...) -> Element | None: ...
    def findall(self, path: str, namespaces: dict[str, str] | None = ...) -> list[Element]: ...
    def findtext(self, path: str, default: str | None = ..., namespaces: dict[str, str] | None = ...) -> str | None: ...
    def get(self, key: str, default: str | None = ...) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...
    def keys(self) -> list[str]: ...
    def items(self) -> list[tuple[str, str]]: ...
    def iter(self, tag: str | None = ...) -> Iterator[Element]: ...
    def iterfind(self, path: str, namespaces: dict[str, str] | None = ...) -> Iterator[Element]: ...
    def clear(self) -> None: ...

class ElementTree:
    def __init__(self, element: Element | None = ..., file: str | IO[bytes] | None = ...) -> None: ...
    def getroot(self) -> Element: ...
    def parse(self, source: str | IO[bytes], parser: XMLParser | None = ...) -> Element: ...
    def write(
        self,
        file_or_filename: str | IO[bytes],
        encoding: str | None = ...,
        xml_declaration: bool | None = ...,
        default_namespace: str | None = ...,
        method: Literal["xml", "html", "text", "c14n"] = ...,
    ) -> None: ...
    def find(self, path: str, namespaces: dict[str, str] | None = ...) -> Element | None: ...
    def findall(self, path: str, namespaces: dict[str, str] | None = ...) -> list[Element]: ...
    def findtext(self, path: str, default: str | None = ..., namespaces: dict[str, str] | None = ...) -> str | None: ...
    def iter(self, tag: str | None = ...) -> Iterator[Element]: ...
    def iterfind(self, path: str, namespaces: dict[str, str] | None = ...) -> Iterator[Element]: ...

class XMLParser:
    def __init__(self, *, target: object | None = ..., encoding: str | None = ...) -> None: ...
    def feed(self, data: str | bytes) -> None: ...
    def close(self) -> Element: ...

class ParseError(SyntaxError):
    code: int
    position: tuple[int, int]

def SubElement(parent: Element, tag: str, attrib: dict[str, str] = ..., **extra: str) -> Element: ...
def parse(source: str | IO[bytes], parser: XMLParser | None = ...) -> ElementTree: ...
def fromstring(text: str | bytes) -> Element: ...
def tostring(element: Element, encoding: str = ..., method: str = ...) -> bytes: ...
